apiVersion: v1
kind: Pod
metadata:
  name: wb
  labels:
    app: nginx
spec:
  containers:
    # an app
    - name: db
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123'
        - name: MYSQL_DATABASE
          value: sananet
    - name: db02
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: '123'
        - name: MYSQL_DATABASE
          value: sananet
    - name: web
      image: nginx

